using System;

/// <summary>
/// Represents a user action log in the user management system.
/// </summary>
/// <remarks>
/// This class is used to log actions performed by users in the system.
/// </remarks>
public class UserActionLog
{
    /// <summary>
    /// Gets or sets the unique identifier for the user action log.
    /// </summary>
    /// <value>The unique identifier for the user action log.</value>
    /// <remarks>
    /// This value is generated by the system and is used to uniquely identify the user action log.
    /// </remarks>
    public long Id { get; set; }

    /// <summary>
    /// Gets or sets the unique identifier for the user.
    /// </summary>
    /// <value>The unique identifier for the user.</value>
    public long UserId { get; set; }

    /// <summary>
    /// Gets or sets the action performed by the user.
    /// </summary>
    /// <value>The action performed by the user.</value>
    public string? Action { get; set; }

    /// <summary>
    /// Gets or sets the date and time when the action was performed.
    /// </summary>
    /// <value>The date and time when the action was performed.</value>
    public DateTime? ActionDate { get; set; }

    /// <summary>
    /// Gets or sets the details of the action.
    /// </summary>
    /// <value>The details of the action.</value>
    public string? Details { get; set; }
}